version: "3.1"

services:
  db:
    image: mysql
    container_name: mysql_nutri-ja
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

    volumes:
      - israelbastos_data:/var/lib/mysql_nutri-ja

volumes:
  israelbastos_data:
