spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nutri-ja_database?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect

  thymeleaf:
    cache: false
