spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nutri-ja_database?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  thymeleaf:
    cache: false

server:
  error:
    whitelabel:
      enabled: false
